"""Add constrained optimization cells to enforce 60/40 blue/red split and Trade Wars variant."""

import json
from pathlib import Path

# Load the notebook
nb_path = Path('notebooks/objective_difficulty_analysis.ipynb')
with open(nb_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# New cells for constrained optimization
new_cells = [
    {
        'cell_type': 'markdown',
        'metadata': {},
        'source': [
            '## 16. Constrained Optimization: Enforce 60/40 Blue/Red Split\n',
            '\n',
            '**Critical Constraint**: The blue/red split should be 60/40 for all player counts.\n',
            '\n',
            'Current configurations violate this:\n',
            '- 2P: 53.3/46.7 (should be 60/40)\n',
            '- 4P-8P: Progressive drift to 73/27\n',
            '\n',
            'Let\'s re-optimize with the proper constraint.'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# Check current blue/red splits\n',
            'print("=" * 80)\n',
            'print("CURRENT BLUE/RED SPLITS (Without 60/40 Constraint)")\n',
            'print("=" * 80)\n',
            '\n',
            'current_splits = {}\n',
            'for pc in [2, 3, 4, 5, 6, 7, 8]:\n',
            '    blue = current_configs[pc]["blue_systems"]\n',
            '    red = current_configs[pc]["red_systems"]\n',
            '    total = blue + red\n',
            '    \n',
            '    blue_pct = (blue / total * 100) if total > 0 else 0\n',
            '    red_pct = (red / total * 100) if total > 0 else 0\n',
            '    \n',
            '    current_splits[pc] = {\n',
            '        "blue": blue,\n',
            '        "red": red,\n',
            '        "total": total,\n',
            '        "blue_pct": blue_pct,\n',
            '        "red_pct": red_pct,\n',
            '        "deviation": abs(blue_pct - 60)\n',
            '    }\n',
            '    \n',
            '    print(f"{pc}P: {blue} blue + {red} red = {total} tiles")\n',
            '    print(f"     Split: {blue_pct:.1f}% blue / {red_pct:.1f}% red")\n',
            '    print(f"     Deviation from 60/40: {abs(blue_pct - 60):.1f} pct points")\n',
            '    print()'
        ]
    },
    {
        'cell_type': 'markdown',
        'metadata': {},
        'source': [
            '## 17. Calculate Target Configurations with 60/40 Split'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            'def calculate_60_40_split(total_non_special_tiles):\n',
            '    """\n',
            '    Calculate blue and red tile counts for 60/40 split.\n',
            '    \n',
            '    Args:\n',
            '        total_non_special_tiles: Total tiles excluding Mecatol and homes\n',
            '    \n',
            '    Returns:\n',
            '        (blue_count, red_count) tuple\n',
            '    """\n',
            '    blue = round(total_non_special_tiles * 0.6)\n',
            '    red = total_non_special_tiles - blue\n',
            '    return blue, red\n',
            '\n',
            '# Calculate proper 60/40 configurations\n',
            'print("=" * 80)\n',
            'print("TARGET CONFIGURATIONS (60/40 Blue/Red Split)")\n',
            'print("=" * 80)\n',
            'print()\n',
            '\n',
            'target_configs = {}\n',
            'for pc in [2, 3, 4, 5, 6, 7, 8]:\n',
            '    current = current_configs[pc]\n',
            '    \n',
            '    # Total non-special = current blue + red\n',
            '    total_non_special = current["blue_systems"] + current["red_systems"]\n',
            '    \n',
            '    # Calculate 60/40 split\n',
            '    blue_target, red_target = calculate_60_40_split(total_non_special)\n',
            '    \n',
            '    target_configs[pc] = {\n',
            '        "blue_systems": blue_target,\n',
            '        "red_systems": red_target,\n',
            '        "total_systems": blue_target + red_target + 1 + pc,  # +1 Mecatol, +pc homes\n',
            '        "mecatol_adjacent": 6,\n',
            '        "edge_tiles": current_configs[pc]["edge_tiles"],  # Keep same for now\n',
            '    }\n',
            '    \n',
            '    blue_delta = blue_target - current["blue_systems"]\n',
            '    red_delta = red_target - current["red_systems"]\n',
            '    \n',
            '    print(f"{pc}P:")\n',
            '    print(f"  Current: {current[\\"blue_systems\\"]} blue + {current[\\"red_systems\\"]} red")\n',
            '    print(f"  Target:  {blue_target} blue + {red_target} red")\n',
            '    print(f"  Changes: {blue_delta:+d} blue, {red_delta:+d} red")\n',
            '    print()'
        ]
    },
    {
        'cell_type': 'markdown',
        'metadata': {},
        'source': [
            '## 18. Trade Wars Variant: Minor Factions for 2P and 3P\n',
            '\n',
            'From the Trade Wars document:\n',
            '- **2P**: 3 Minor Faction systems, 9 blue, 8 red\n',
            '- **3P**: 3 Minor Faction systems, 10 blue, 8 red\n',
            '\n',
            'Minor Faction systems:\n',
            '- Replace 3 blue tiles\n',
            '- Act as additional "home" systems (but not true homes)\n',
            '- Include monuments and space stations\n',
            '- Planets have all three traits (cultural, industrial, hazardous)'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# Calculate Trade Wars configurations with proper 60/40 split\n',
            'print("=" * 80)\n',
            'print("TRADE WARS VARIANT (2P and 3P with Minor Factions)")\n',
            'print("=" * 80)\n',
            'print()\n',
            '\n',
            'trade_wars_configs = {}\n',
            '\n',
            '# 2P Trade Wars\n',
            'print("2 PLAYER TRADE WARS:")\n',
            'print("  Components:")\n',
            'print("    - 2 player home systems")\n',
            'print("    - 3 minor faction systems (replacing 3 blue tiles)")\n',
            'print("    - 1 Mecatol Rex")\n',
            'print("    - Blue and red tiles (60/40 split)")\n',
            'print()\n',
            '\n',
            '# From document: 23 total systems\n',
            'total_2p = 23\n',
            'homes_2p = 2\n',
            'minor_factions_2p = 3\n',
            'mecatol = 1\n',
            'non_special_2p = total_2p - homes_2p - minor_factions_2p - mecatol\n',
            '\n',
            'blue_2p, red_2p = calculate_60_40_split(non_special_2p)\n',
            '\n',
            'trade_wars_configs[2] = {\n',
            '    "total_systems": total_2p,\n',
            '    "homes": homes_2p,\n',
            '    "minor_factions": minor_factions_2p,\n',
            '    "mecatol": mecatol,\n',
            '    "blue_systems": blue_2p,\n',
            '    "red_systems": red_2p,\n',
            '    "edge_tiles": 6,  # From document: small maps\n',
            '    "monuments": 3,  # One per minor faction\n',
            '    "space_stations": 3,  # One per minor faction\n',
            '}\n',
            '\n',
            'print(f"  Tile breakdown:")\n',
            'print(f"    Total: {total_2p} systems")\n',
            'print(f"    - {homes_2p} player homes")\n',
            'print(f"    - {minor_factions_2p} minor faction systems")\n',
            'print(f"    - {mecatol} Mecatol Rex")\n',
            'print(f"    - {blue_2p} blue tiles (60%)")\n',
            'print(f"    - {red_2p} red tiles (40%)")\n',
            'print(f"    = {homes_2p + minor_factions_2p + mecatol + blue_2p + red_2p} total")\n',
            'print()\n',
            '\n',
            '# 3P Trade Wars  \n',
            'print("3 PLAYER TRADE WARS:")\n',
            'print("  Components:")\n',
            'print("    - 3 player home systems")\n',
            'print("    - 3 minor faction systems (replacing 3 blue tiles)")\n',
            'print("    - 1 Mecatol Rex")\n',
            'print("    - Blue and red tiles (60/40 split)")\n',
            'print()\n',
            '\n',
            '# From document: 25 total systems\n',
            'total_3p = 25\n',
            'homes_3p = 3\n',
            'minor_factions_3p = 3\n',
            'non_special_3p = total_3p - homes_3p - minor_factions_3p - mecatol\n',
            '\n',
            'blue_3p, red_3p = calculate_60_40_split(non_special_3p)\n',
            '\n',
            'trade_wars_configs[3] = {\n',
            '    "total_systems": total_3p,\n',
            '    "homes": homes_3p,\n',
            '    "minor_factions": minor_factions_3p,\n',
            '    "mecatol": mecatol,\n',
            '    "blue_systems": blue_3p,\n',
            '    "red_systems": red_3p,\n',
            '    "edge_tiles": 12,  # Medium maps\n',
            '    "monuments": 3,\n',
            '    "space_stations": 3,\n',
            '}\n',
            '\n',
            'print(f"  Tile breakdown:")\n',
            'print(f"    Total: {total_3p} systems")\n',
            'print(f"    - {homes_3p} player homes")\n',
            'print(f"    - {minor_factions_3p} minor faction systems")\n',
            'print(f"    - {mecatol} Mecatol Rex")\n',
            'print(f"    - {blue_3p} blue tiles (60%)")\n',
            'print(f"    - {red_3p} red tiles (40%)")\n',
            'print(f"    = {homes_3p + minor_factions_3p + mecatol + blue_3p + red_3p} total")\n',
            'print()'
        ]
    },
    {
        'cell_type': 'markdown',
        'metadata': {},
        'source': [
            '## 19. Economic Impact: Monuments and Space Stations\n',
            '\n',
            'Model the economic value of Trade Wars components using the CC baseline:\n',
            '\n',
            '**Monuments** (3 per map):\n',
            '- Accumulate 1 commodity per status phase\n',
            '- Worth 1 VP per 3 commodities\n',
            '- Can be captured or destroyed\n',
            '\n',
            '**Space Stations** (3 per map):\n',
            '- +1 commodity value when controlled\n',
            '- Can exhaust to convert commodities to TG\n',
            '- Acts as planet for resource/influence'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# Calculate economic value using CC baseline\n',
            'print("=" * 80)\n',
            'print("ECONOMIC VALUE OF TRADE WARS COMPONENTS (CC Baseline)")\n',
            'print("=" * 80)\n',
            'print()\n',
            '\n',
            '# Conversion rates from unified framework\n',
            'TG_TO_CC = 0.6  # 1 TG = 0.6 CC (mid-range)\n',
            'COMMODITY_TO_TG = 1  # 1 commodity = 1 TG when converted\n',
            '\n',
            'print("MONUMENTS:")\n',
            'print("  Accumulation rate: 1 commodity/status phase")\n',
            'print("  VP value: 1 VP per 3 commodities accumulated")\n',
            'print("  Economic value calculation:")\n',
            'print("    - Per round: 1 commodity = 1 TG potential = 0.6 CC")\n',
            'print("    - Over 10 rounds: ~10 commodities = ~6 CC")\n',
            'print("    - VP conversion: 3 commodities -> 1 VP (priceless)")\n',
            'print("    - Net: Primarily VP generation mechanism")\n',
            'print()\n',
            '\n',
            'print("SPACE STATIONS:")\n',
            'print("  +1 commodity value when controlled")\n',
            'print("  Economic value calculation:")\n',
            'print("    - Effective +1 TG income per round (from trading)")\n',
            'print("    - Value: +0.6 CC/round")\n',
            'print("    - Over 10 rounds: ~6 CC total value")\n',
            'print("    - Plus: Can exhaust for immediate conversion")\n',
            'print()\n',
            '\n',
            'print("MINOR FACTION SYSTEMS:")\n',
            'print("  Components:")\n',
            'print("    - Multiple planets with all 3 traits")\n',
            'print("    - 1 monument")\n',
            'print("    - 1 space station")\n',
            'print("    - 3 neutral infantry (starting defense)")\n',
            'print("  Total system value:")\n',
            '\n',
            '# Estimate minor faction system value\n',
            '# Assume ~2-3 planets per system with mixed resources/influence\n',
            'avg_planets_per_mf = 2.5\n',
            'avg_resources_per_planet = 1.5  # Mid-tier planets\n',
            'avg_influence_per_planet = 1.5\n',
            '\n',
            'planet_value_cc = avg_planets_per_mf * max(\n',
            '    avg_resources_per_planet * CONVERSION_RATES["resources_to_cc"],\n',
            '    avg_influence_per_planet * CONVERSION_RATES["influence_to_cc"]\n',
            ')\n',
            '\n',
            'space_station_value_10_rounds = 6  # CC\n',
            'monument_value_10_rounds = 6  # CC (plus VP)\n',
            '\n',
            'total_mf_value_per_round = planet_value_cc + 0.6 + 0.6  # planets + station + monument\n',
            '\n',
            'print(f"    - Planets: ~{planet_value_cc:.1f} CC/round")\n',
            'print(f"    - Space station: 0.6 CC/round")\n',
            'print(f"    - Monument: 0.6 CC/round + VP generation")\n',
            'print(f"    - Total: ~{total_mf_value_per_round:.1f} CC/round")\n',
            'print(f"    - Over 10 rounds: ~{total_mf_value_per_round * 10:.0f} CC")\n',
            'print()\n',
            '\n',
            'print("TOTAL ECONOMIC BOOST FOR 2P/3P TRADE WARS:")\n',
            'print(f"  3 minor faction systems x {total_mf_value_per_round:.1f} CC/round")\n',
            'print(f"  = {3 * total_mf_value_per_round:.1f} CC/round table-wide")\n',
            'print(f"  = {3 * total_mf_value_per_round / 2:.1f} CC/round per player (2P)")\n',
            'print(f"  = {3 * total_mf_value_per_round / 3:.1f} CC/round per player (3P)")\n',
            'print()\n',
            'print("This represents significant economic acceleration for low player counts.")'
        ]
    },
    {
        'cell_type': 'markdown',
        'metadata': {},
        'source': [
            '## 20. Comparison: Standard vs Trade Wars for 2P/3P\n',
            '\n',
            'Compare balance metrics between standard rules and Trade Wars variant.'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# Create comparison dataframe\n',
            'comparison_data = []\n',
            '\n',
            'for pc in [2, 3]:\n',
            '    # Standard configuration (with 60/40 correction)\n',
            '    std_blue, std_red = calculate_60_40_split(\n',
            '        current_configs[pc]["blue_systems"] + current_configs[pc]["red_systems"]\n',
            '    )\n',
            '    \n',
            '    comparison_data.append({\n',
            '        "Config": f"{pc}P Standard",\n',
            '        "Blue Tiles": std_blue,\n',
            '        "Red Tiles": std_red,\n',
            '        "Minor Factions": 0,\n',
            '        "Monuments": 0,\n',
            '        "Space Stations": 0,\n',
            '        "Total Systems": std_blue + std_red + 1 + pc,\n',
            '        "Economic Boost (CC/round/player)": 0,\n',
            '    })\n',
            '    \n',
            '    # Trade Wars configuration\n',
            '    tw = trade_wars_configs[pc]\n',
            '    comparison_data.append({\n',
            '        "Config": f"{pc}P Trade Wars",\n',
            '        "Blue Tiles": tw["blue_systems"],\n',
            '        "Red Tiles": tw["red_systems"],\n',
            '        "Minor Factions": tw["minor_factions"],\n',
            '        "Monuments": tw["monuments"],\n',
            '        "Space Stations": tw["space_stations"],\n',
            '        "Total Systems": tw["total_systems"],\n',
            '        "Economic Boost (CC/round/player)": round(3 * total_mf_value_per_round / pc, 1),\n',
            '    })\n',
            '\n',
            'comparison_df = pd.DataFrame(comparison_data)\n',
            '\n',
            'print("=" * 80)\n',
            'print("STANDARD vs TRADE WARS COMPARISON")\n',
            'print("=" * 80)\n',
            'print()\n',
            'print(comparison_df.to_string(index=False))\n',
            'print()\n',
            '\n',
            '# Visualize\n',
            'fig, axes = plt.subplots(1, 2, figsize=(14, 6))\n',
            '\n',
            '# Tile counts comparison\n',
            'ax = axes[0]\n',
            'configs = ["2P Std", "2P TW", "3P Std", "3P TW"]\n',
            'blue_counts = [comparison_data[i]["Blue Tiles"] for i in range(4)]\n',
            'red_counts = [comparison_data[i]["Red Tiles"] for i in range(4)]\n',
            'mf_counts = [comparison_data[i]["Minor Factions"] for i in range(4)]\n',
            '\n',
            'x = np.arange(len(configs))\n',
            'width = 0.25\n',
            '\n',
            'ax.bar(x - width, blue_counts, width, label="Blue", color="#3498db")\n',
            'ax.bar(x, red_counts, width, label="Red", color="#e74c3c")\n',
            'ax.bar(x + width, mf_counts, width, label="Minor Factions", color="#f39c12")\n',
            '\n',
            'ax.set_xlabel("Configuration", fontsize=12)\n',
            'ax.set_ylabel("Tile Count", fontsize=12)\n',
            'ax.set_title("Tile Distribution: Standard vs Trade Wars", fontweight="bold")\n',
            'ax.set_xticks(x)\n',
            'ax.set_xticklabels(configs)\n',
            'ax.legend()\n',
            'ax.grid(True, alpha=0.3, axis="y")\n',
            '\n',
            '# Economic boost\n',
            'ax = axes[1]\n',
            'econ_boost = [comparison_data[i]["Economic Boost (CC/round/player)"] for i in range(4)]\n',
            'colors = ["#95a5a6", "#2ecc71", "#95a5a6", "#2ecc71"]\n',
            'ax.bar(configs, econ_boost, color=colors, edgecolor="black")\n',
            'ax.set_xlabel("Configuration", fontsize=12)\n',
            'ax.set_ylabel("CC per Round per Player", fontsize=12)\n',
            'ax.set_title("Economic Boost from Trade Wars Variant", fontweight="bold")\n',
            'ax.grid(True, alpha=0.3, axis="y")\n',
            '\n',
            'plt.tight_layout()\n',
            'plt.show()'
        ]
    },
    {
        'cell_type': 'markdown',
        'metadata': {},
        'source': [
            '## 21. Final Recommendations with 60/40 Constraint\n',
            '\n',
            'Comprehensive recommendations for all player counts with proper blue/red split.'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            'print("=" * 80)\n',
            'print("FINAL RECOMMENDATIONS: 60/40 BLUE/RED SPLIT ENFORCED")\n',
            'print("=" * 80)\n',
            'print()\n',
            '\n',
            'print("STANDARD CONFIGURATIONS (4P-8P):")\n',
            'print("-" * 80)\n',
            'for pc in [4, 5, 6, 7, 8]:\n',
            '    target = target_configs[pc]\n',
            '    current = current_configs[pc]\n',
            '    \n',
            '    blue_change = target["blue_systems"] - current["blue_systems"]\n',
            '    red_change = target["red_systems"] - current["red_systems"]\n',
            '    \n',
            '    print(f"\\n{pc} PLAYERS:")\n',
            '    print(f"  Blue tiles: {current[\\"blue_systems\\"]} -> {target[\\"blue_systems\\"]} ({blue_change:+d})")\n',
            '    print(f"  Red tiles:  {current[\\"red_systems\\"]} -> {target[\\"red_systems\\"]} ({red_change:+d})")\n',
            '    print(f"  Total systems: {target[\\"total_systems\\"]}")\n',
            '    print(f"  Split: 60% blue / 40% red")\n',
            '\n',
            'print("\\n\\n" + "=" * 80)\n',
            'print("TRADE WARS VARIANT (2P-3P):")\n',
            'print("-" * 80)\n',
            'for pc in [2, 3]:\n',
            '    tw = trade_wars_configs[pc]\n',
            '    print(f"\\n{pc} PLAYERS:")\n',
            '    print(f"  Player homes: {tw[\\"homes\\"]}")\n',
            '    print(f"  Minor faction systems: {tw[\\"minor_factions\\"]}")\n',
            '    print(f"  Mecatol Rex: {tw[\\"mecatol\\"]}")\n',
            '    print(f"  Blue tiles: {tw[\\"blue_systems\\"]}")\n',
            '    print(f"  Red tiles: {tw[\\"red_systems\\"]}")\n',
            '    print(f"  Total systems: {tw[\\"total_systems\\"]}")\n',
            '    print(f"  Split: 60% blue / 40% red (non-special tiles)")\n',
            '    print(f"  Monuments: {tw[\\"monuments\\"]}")\n',
            '    print(f"  Space stations: {tw[\\"space_stations\\"]}")\n',
            '    print(f"  Economic boost: {round(3 * total_mf_value_per_round / pc, 1)} CC/round/player")\n',
            '\n',
            'print("\\n\\n" + "=" * 80)\n',
            'print("KEY FINDINGS:")\n',
            'print("=" * 80)\n',
            'print("\\n1. BLUE/RED SPLIT:")\n',
            'print("   - Current configs deviate significantly from 60/40")\n',
            'print("   - Worst case: 8P at 73/27 (13 percentage points off)")\n',
            'print("   - Recommendation: Enforce 60/40 for all player counts")\n',
            'print("\\n2. TRADE WARS VARIANT (2P/3P):")\n',
            'print("   - Adds significant economic acceleration via minor factions")\n',
            'print("   - Monuments provide VP generation mechanism")\n',
            'print("   - Space stations increase commodity economy")\n',
            'print("   - Hypothesis: This compensates for reduced social dynamics")\n',
            'print("\\n3. TESTING RECOMMENDATIONS:")\n',
            'print("   - Test 2P/3P with Trade Wars variant vs standard")\n',
            'print("   - Measure objective completion rates")\n',
            'print("   - Track game length and VP progression")\n',
            'print("   - Compare to 6P baseline experience")\n',
            'print("\\n" + "=" * 80)'
        ]
    }
]

# Append new cells
nb['cells'].extend(new_cells)

# Save updated notebook
with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=2)

print(f'Added {len(new_cells)} cells to notebook')
print(f'Total cells: {len(nb["cells"])}')
