"""Add robust optimization cells to the objective difficulty analysis notebook."""

import json
from pathlib import Path

# Load the notebook
nb_path = Path('notebooks/objective_difficulty_analysis.ipynb')
with open(nb_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# New cells for robust optimization
new_cells = [
    {
        'cell_type': 'markdown',
        'metadata': {},
        'source': [
            '## 10. Load Map Statistics\n',
            '\n',
            'Load current map configurations to understand tile counts and geometry.'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# Load map statistics\n',
            "with open(DATA_DIR / 'map_statistics.json') as f:\n",
            '    map_stats = json.load(f)\n',
            '\n',
            '# Extract current configurations\n',
            'current_configs = {}\n',
            "for pc_str, data in map_stats['by_player_count'].items():\n",
            '    pc = int(pc_str)\n',
            "    geometry = data['geometry']\n",
            '    current_configs[pc] = {\n',
            "        'blue_systems': geometry['blue_systems'],\n",
            "        'red_systems': geometry['red_systems'],\n",
            "        'total_systems': geometry['total_systems'],\n",
            "        'mecatol_adjacent': 6,  # Mecatol Rex always has 6 adjacent tiles\n",
            '    }\n',
            '\n',
            '# Calculate edge tiles (approximation based on hex geometry)\n',
            'def estimate_edge_tiles(total_systems, player_count):\n',
            '    """Estimate number of edge tiles based on map geometry."""\n',
            '    # Simplified estimation - actual depends on map shape\n',
            '    if player_count <= 3:\n',
            '        return 6  # Small maps have ~6 edge positions\n',
            '    elif player_count <= 4:\n',
            '        return 12  # Medium maps\n',
            '    elif player_count <= 6:\n',
            '        return 18  # Standard maps\n',
            '    else:\n',
            '        return 24  # Large maps\n',
            '\n',
            'for pc in current_configs:\n',
            "    current_configs[pc]['edge_tiles'] = estimate_edge_tiles(\n",
            "        current_configs[pc]['total_systems'], pc\n",
            '    )\n',
            '\n',
            'print("=" * 80)\n',
            'print("CURRENT MAP CONFIGURATIONS")\n',
            'print("=" * 80)\n',
            'config_df = pd.DataFrame(current_configs).T\n',
            "config_df.index.name = 'Players'\n",
            'print("\\n", config_df.to_string())'
        ]
    },
    {
        'cell_type': 'markdown',
        'metadata': {},
        'source': [
            '## 11. Objective-Driven Tile Requirements\n',
            '\n',
            'Calculate how many tiles of each type are needed to support map-dependent objectives.'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# Map requirement types to tile categories\n',
            'TILE_REQUIREMENTS = {\n',
            "    'edge_systems': 'edge_tiles',\n",
            "    'empty_systems': 'blue_systems',  # Empty systems are part of blue tiles\n",
            "    'adjacent_to_mecatol': 'mecatol_adjacent',\n",
            "    'legendary_or_anomaly_systems': 'blue_systems',\n",
            "    'anomaly_systems': 'blue_systems',\n",
            '}\n',
            '\n',
            '# Calculate requirements for high-variance objectives\n',
            'print("=" * 80)\n',
            'print("TILE REQUIREMENTS FROM HIGH-VARIANCE OBJECTIVES")\n',
            'print("=" * 80)\n',
            '\n',
            'high_var_map_dependent = high_var[\n',
            "    high_var['requirement_type'].isin(TILE_REQUIREMENTS.keys())\n",
            ']\n',
            '\n',
            'print("\\nHigh-variance map-dependent objectives:")\n',
            'for idx, row in high_var_map_dependent.iterrows():\n',
            "    req_val = row['requirement_value']\n",
            "    tile_type = TILE_REQUIREMENTS.get(row['requirement_type'], 'unknown')\n",
            "    print(f\"  • {row['objective']} ({row['stage']})\")\n",
            "    print(f\"    Requires: {req_val} {row['requirement_type']} -> {tile_type}\")\n",
            "    print(f\"    Variability: {row['variability_score']:.3f} (CV: {row['cv_difficulty']:.3f})\")\n",
            '    print()'
        ]
    },
    {
        'cell_type': 'markdown',
        'metadata': {},
        'source': [
            '## 12. Robust Optimization: Minimize Objective Difficulty Variance\n',
            '\n',
            'Use optimization to find tile configurations that minimize variance in objective difficulty across player counts.\n',
            '\n',
            '**Objective Function**: Minimize weighted sum of:\n',
            '1. Total variance across all objectives\n',
            '2. Deviation from 6-player baseline\n',
            '3. Penalty for extreme configurations'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            'from scipy.optimize import differential_evolution, Bounds\n',
            '\n',
            'def objective_difficulty_variance(tiles, player_count, objectives_df):\n',
            '    """\n',
            '    Calculate total variance in objective difficulty for a given tile configuration.\n',
            '    \n',
            '    Parameters:\n',
            '    - tiles: array [blue_systems, edge_tiles]\n',
            '    - player_count: int\n',
            '    - objectives_df: DataFrame with objective data\n',
            '    \n',
            '    Returns: total variance score (lower is better)\n',
            '    """\n',
            '    blue_systems, edge_tiles = tiles\n',
            '    mecatol_adjacent = 6  # Fixed by game rules\n',
            '    \n',
            '    # Calculate per-player availability\n',
            '    blue_per_player = blue_systems / player_count\n',
            '    edge_per_player = edge_tiles / player_count\n',
            '    mecatol_per_player = mecatol_adjacent / player_count\n',
            '    \n',
            '    # Get 6-player baseline for comparison\n',
            "    baseline_blue = current_configs[6]['blue_systems'] / 6\n",
            "    baseline_edge = current_configs[6]['edge_tiles'] / 6\n",
            '    \n',
            '    # Calculate difficulty adjustments for map-dependent objectives\n',
            '    variance_scores = []\n',
            '    \n',
            '    for idx, row in objectives_df.iterrows():\n',
            "        req_type = row['requirement_type']\n",
            "        req_val = row['requirement_value']\n",
            '        \n',
            "        if req_type == 'edge_systems':\n",
            '            # Difficulty inversely proportional to edge availability\n',
            '            difficulty = req_val / max(edge_per_player, 1)\n',
            '            baseline_diff = req_val / max(baseline_edge, 1)\n',
            "        elif req_type in ['empty_systems', 'legendary_or_anomaly_systems', 'anomaly_systems']:\n",
            '            difficulty = req_val / max(blue_per_player, 1)\n',
            '            baseline_diff = req_val / max(baseline_blue, 1)\n',
            "        elif req_type == 'adjacent_to_mecatol':\n",
            '            difficulty = req_val / max(mecatol_per_player, 1)\n',
            '            baseline_diff = req_val / max(6/6, 1)  # Always 6 adjacent\n',
            '        else:\n',
            '            continue\n',
            '        \n',
            '        # Squared deviation from baseline\n',
            '        variance_scores.append((difficulty - baseline_diff) ** 2)\n',
            '    \n',
            '    # Total variance + penalty for extreme values\n',
            '    total_variance = np.sum(variance_scores) if variance_scores else 0\n',
            '    \n',
            '    # Penalty for configurations too far from 6-player ratios\n',
            '    ratio_penalty = (\n',
            '        ((blue_per_player - baseline_blue) / baseline_blue) ** 2 +\n',
            '        ((edge_per_player - baseline_edge) / baseline_edge) ** 2\n',
            '    ) * 10  # Weight ratio preservation\n',
            '    \n',
            '    return total_variance + ratio_penalty\n',
            '\n',
            'print("✓ Optimization function defined")'
        ]
    },
    {
        'cell_type': 'markdown',
        'metadata': {},
        'source': [
            '## 13. Optimize Tile Configurations for Each Player Count'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# Run optimization for each player count\n',
            'optimal_configs = {}\n',
            '\n',
            'print("=" * 80)\n',
            'print("OPTIMIZING TILE CONFIGURATIONS")\n',
            'print("=" * 80)\n',
            '\n',
            'for pc in [2, 3, 4, 5, 6, 7, 8]:\n',
            '    print(f"\\nOptimizing for {pc} players...")\n',
            '    \n',
            '    # Define bounds (reasonable ranges based on current configs)\n',
            '    current = current_configs[pc]\n',
            '    bounds = [\n',
            "        (max(10, current['blue_systems'] - 10), current['blue_systems'] + 10),  # blue_systems\n",
            "        (max(6, current['edge_tiles'] - 6), current['edge_tiles'] + 6),        # edge_tiles\n",
            '    ]\n',
            '    \n',
            '    # Optimization\n',
            '    result = differential_evolution(\n',
            '        lambda x: objective_difficulty_variance(x, pc, high_var_map_dependent),\n',
            '        bounds=bounds,\n',
            '        seed=42,\n',
            '        maxiter=100,\n',
            '        atol=1e-4,\n',
            '        tol=1e-4,\n',
            '        workers=1,\n',
            "        updating='immediate'\n",
            '    )\n',
            '    \n',
            '    blue_opt, edge_opt = result.x\n',
            '    optimal_configs[pc] = {\n',
            "        'blue_systems': int(round(blue_opt)),\n",
            "        'edge_tiles': int(round(edge_opt)),\n",
            "        'mecatol_adjacent': 6,\n",
            "        'total_systems': int(round(blue_opt)) + current['red_systems'] + 1,  # +1 for Mecatol\n",
            "        'variance_score': result.fun,\n",
            "        'current_blue': current['blue_systems'],\n",
            "        'current_edge': current['edge_tiles'],\n",
            '    }\n',
            '    \n',
            "    print(f\"  Current: {current['blue_systems']} blue, {current['edge_tiles']} edge\")\n",
            "    print(f\"  Optimal: {optimal_configs[pc]['blue_systems']} blue, {optimal_configs[pc]['edge_tiles']} edge\")\n",
            '    print(f"  Variance reduction: {result.fun:.4f}")\n',
            '\n',
            'print("\\n✓ Optimization complete")'
        ]
    },
    {
        'cell_type': 'markdown',
        'metadata': {},
        'source': [
            '## 14. Compare Current vs Optimal Configurations'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            '# Create comparison table\n',
            'comparison_rows = []\n',
            '\n',
            'for pc in [2, 3, 4, 5, 6, 7, 8]:\n',
            '    current = current_configs[pc]\n',
            '    optimal = optimal_configs[pc]\n',
            '    \n',
            '    comparison_rows.append({\n',
            "        'Players': pc,\n",
            "        'Current Blue': current['blue_systems'],\n",
            "        'Optimal Blue': optimal['blue_systems'],\n",
            "        'Blue Δ': optimal['blue_systems'] - current['blue_systems'],\n",
            "        'Current Edge': current['edge_tiles'],\n",
            "        'Optimal Edge': optimal['edge_tiles'],\n",
            "        'Edge Δ': optimal['edge_tiles'] - current['edge_tiles'],\n",
            "        'Variance Score': optimal['variance_score'],\n",
            '    })\n',
            '\n',
            'comparison_df = pd.DataFrame(comparison_rows)\n',
            "comparison_df.set_index('Players', inplace=True)\n",
            '\n',
            'print("=" * 80)\n',
            'print("CURRENT vs OPTIMAL TILE CONFIGURATIONS")\n',
            'print("=" * 80)\n',
            'print("\\n", comparison_df.to_string())\n',
            '\n',
            '# Visualize\n',
            'fig, axes = plt.subplots(1, 2, figsize=(14, 6))\n',
            '\n',
            '# 14a. Blue systems comparison\n',
            'ax = axes[0]\n',
            'x = comparison_df.index\n',
            'width = 0.35\n',
            "ax.bar(x - width/2, comparison_df['Current Blue'], width, label='Current', color='#3498db', alpha=0.7)\n",
            "ax.bar(x + width/2, comparison_df['Optimal Blue'], width, label='Optimal', color='#2ecc71', alpha=0.7)\n",
            "ax.set_xlabel('Player Count', fontsize=12)\n",
            "ax.set_ylabel('Blue Systems', fontsize=12)\n",
            "ax.set_title('Blue Systems: Current vs Optimal', fontweight='bold')\n",
            'ax.legend()\n',
            "ax.grid(True, alpha=0.3, axis='y')\n",
            '\n',
            '# 14b. Edge tiles comparison\n',
            'ax = axes[1]\n',
            "ax.bar(x - width/2, comparison_df['Current Edge'], width, label='Current', color='#e74c3c', alpha=0.7)\n",
            "ax.bar(x + width/2, comparison_df['Optimal Edge'], width, label='Optimal', color='#f39c12', alpha=0.7)\n",
            "ax.set_xlabel('Player Count', fontsize=12)\n",
            "ax.set_ylabel('Edge Tiles', fontsize=12)\n",
            "ax.set_title('Edge Tiles: Current vs Optimal', fontweight='bold')\n",
            'ax.legend()\n',
            "ax.grid(True, alpha=0.3, axis='y')\n",
            '\n',
            'plt.tight_layout()\n',
            'plt.show()'
        ]
    },
    {
        'cell_type': 'markdown',
        'metadata': {},
        'source': [
            '## 15. Final Recommendations\n',
            '\n',
            'Based on the robust optimization analysis, here are the recommended tile configurations for each player count.'
        ]
    },
    {
        'cell_type': 'code',
        'execution_count': None,
        'metadata': {},
        'outputs': [],
        'source': [
            'print("=" * 80)\n',
            'print("FINAL RECOMMENDATIONS: OPTIMAL TILE CONFIGURATIONS")\n',
            'print("=" * 80)\n',
            '\n',
            'recommendations_df = pd.DataFrame(optimal_configs).T\n',
            "recommendations_df.index.name = 'Players'\n",
            "recommendations_df = recommendations_df[['blue_systems', 'edge_tiles', 'mecatol_adjacent', 'total_systems']]\n",
            '\n',
            'print("\\nRecommended Configurations:")\n',
            'print(recommendations_df.to_string())\n',
            '\n',
            'print("\\n\\nKey Changes from Current:")\n',
            'for pc in [2, 3, 4, 5, 6, 7, 8]:\n',
            "    blue_delta = optimal_configs[pc]['blue_systems'] - optimal_configs[pc]['current_blue']\n",
            "    edge_delta = optimal_configs[pc]['edge_tiles'] - optimal_configs[pc]['current_edge']\n",
            '    \n',
            '    if abs(blue_delta) > 0 or abs(edge_delta) > 0:\n',
            '        print(f"\\n{pc} Players:")\n',
            '        if abs(blue_delta) > 0:\n',
            "            direction = 'increase' if blue_delta > 0 else 'decrease'\n",
            '            print(f"  • {direction.capitalize()} blue systems by {abs(blue_delta)}")\n',
            '        if abs(edge_delta) > 0:\n',
            "            direction = 'increase' if edge_delta > 0 else 'decrease'\n",
            '            print(f"  • {direction.capitalize()} edge tiles by {abs(edge_delta)}")\n',
            '    else:\n',
            '        print(f"\\n{pc} Players: Current configuration is optimal")\n',
            '\n',
            'print("\\n" + "=" * 80)\n',
            'print("ANALYSIS COMPLETE")\n',
            'print("=" * 80)\n',
            'print("\\nThese recommendations minimize objective difficulty variance while")\n',
            'print("maintaining balance relative to the 6-player baseline experience.")'
        ]
    }
]

# Append new cells
nb['cells'].extend(new_cells)

# Save updated notebook
with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=2)

print(f'Added {len(new_cells)} cells to notebook')
print(f'Total cells: {len(nb["cells"])}')
